-- Optional: if you want case-insensitive email handling later
create extension if not exists citext;

drop table if exists cost_projections cascade;
drop table if exists cost_analyses cascade;
drop table if exists transportation_costs cascade;
drop table if exists commuting_logs cascade;
drop table if exists profiles cascade;

create table profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    first_name varchar(100),
    last_name varchar(100),
    email citext unique
);

create table commuting_logs (
    log_id integer generated by default as identity primary key,
    user_id uuid references profiles(id) on delete cascade,
    transportation_mode varchar(50),
    date_added timestamp default current_timestamp,
    duration_in_minutes integer,
    commute_type varchar(50) default 'Work',
    distance_in_miles double precision,
    cost numeric(8,2)
);

create table cost_analyses (
    analysis_id integer generated by default as identity primary key,
    user_id uuid references profiles(id) on delete cascade,
    commute_type varchar(50),
    one_year_cost double precision,
    two_year_cost double precision,
    five_year_cost double precision,
    total_cost double precision
);

create table transportation_costs (
    profile_id integer generated by default as identity primary key,
    user_id uuid references profiles(id) on delete cascade,
    insurance_cost double precision,
    vehicle_type varchar(50),
    fuel_cost double precision default 3.5,
    maintenance_cost double precision,
    public_transport_cost double precision,
    created_date timestamp default current_timestamp,
    miles_per_gallon double precision default 25,
    monthly_payment double precision default 200,
    column_name integer
);

create table cost_projections (
    log_id integer primary key references commuting_logs(log_id) on delete cascade,
    user_id uuid not null references profiles(id) on delete cascade,
    transportation_mode varchar(50),
    date_added timestamp default current_timestamp,
    duration_in_minutes integer,
    distance_in_miles double precision
);